### ISSUE TITLE
[Card] Content model documentation 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#1095]
Create content model of [Card](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-card--default) component. 

Referencing format of the current one, but feel free to propose improvements. 
Example of current documentation of content model as a table: https://www.ibm.com/standards/carbon/components/callout-quote#content-guidance

**Comment by JBrandwine** [comment]
[https://app.zenhub.com/files/202376156/0cafd109-d3e3-4c9f-b160-2cdc7678e9fe/download](https://app.zenhub.com/files/202376156/0cafd109-d3e3-4c9f-b160-2cdc7678e9fe/download)

Hi @shixiedesign,

This is ready for review.

Note, there are some questions in the doc. Also, card section and card section images already have content models but I included them as to be updated, both for the new heading names and because I have a couple of questions about them.

Components included are:
Card
Card group
Card in card
Card link
Card section
Card carousel
Card section images

**Comment by shixiedesign** [comment]
Reviewed and answered questions. There are a few more things to figure out, so rolling into next sprint to get more time. Also will need to loop in @RichKummer 's ticket #6643 as well.

**Comment by JBrandwine** [comment]
@shixiedesign 

See attached for the card components we reviewed today.

Thanks!

[https://app.zenhub.com/files/202376156/d1918f88-a36b-454b-a151-836810ef8f03/download](https://app.zenhub.com/files/202376156/d1918f88-a36b-454b-a151-836810ef8f03/download)
