### ISSUE TITLE
[Website] Overview

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-website#1590]
### V1 Fix
- Drop list view
- Update gallery links so not missing any
   - Jeannie has master file?

---

### Intro
OK, need to consider if we want to rewrite the types of "UI or layout problems" we list

### List of components
- List
   - Clean up list
   - OR kill it (ideal) really challenging to maintain the "purpose" and update the stable/ etc. All WC are stable
- Gallery
   - Transition gallery as the Overview page (no tabs)
   - Need to rename any components that are renamed 
   - Remove any components we deprecated
   - Need new images for many components...
      - Card (stroke + icon placement)
      - Card in card (stroke + icon placement)
      - Card link (stroke + icon placement)
      - Dotcom shell (masthead + light footer)
      - Feature card (stroke + light card)
      - Footer (light)
      - Link list (non card)
      - Locale modal? (icon placement)
      - Tags (fix linking – may not need tags)
      - Callout quote
      - Callout media
      - Card group (stroke + icon placement)
      - Feature section
      - Lead space (light)
      - Callout (light)
      - Callout media (light)
      - Card group (stroke + icon placement)
      - Feature section (light)
      - Lead space (light)
      - Lead space block (light)

**Comment by jeanservaas** [comment]
I went through the whole storybook because Diana Stanciulescu and Dana Paslaru from Brand have taken over the UI Imagery kit (from Alex Ku) and are moving it into Figma and creating more robust guidance around product UI illustrations.

Below should now be a comprehensive list of everything we'll need a thumbnail for in v2; we need to double check that all of the correct components have been removed as well (like the content blocks etc.)

- [x] back-to-top
- [x] button-group
- [x] button
- [x] callout-quote
- [x] callout-with-media
- [x] card-group
- [x] card-in-card
- [x] card-link
- [x] card-section-carousel
- [x] card-section-offset
- [x] card-section
- [x] card
- [x] carousel
- [x] content-group-banner
- [x] content-group-cards
- [x] content-group-pictograms
- [x] content-group
- [x] content-item-horizontal
- [x] content-item
- [x] content-section
- [x] cta-block
- [x] call-to-action
- [x] dotcom-shell
- [x] expressive-modal
- [x] feature-card
- [x] feature-section
- [x] filter-panel
- [x] footer
- [x] horizontal-rule
- [x] image
- [x] leadspace-block
- [x] leadspace-search
- [x] leadspace
- [x] leaving-ibm
- [x] lightbox-media-viewer
- [x] link-list-section
- [x] link-list
- [x] link-with-icon
- [x] locale-modal
- [x] logo-grid
- [x] masthead
- [x] pictogram-item
- [x] quote
- [ ] scroll-animations
- [x] search-with-typeahead
- [x] structured-list
- [x] table-of-contents
- [x] tabs-extended
- [ ] tag-group
- [ ] tag-link
- [x] universal-banner
- [x] video-player

**Comment by jeanservaas** [comment]
## Final PNGs

[Dotcom_overview.zip](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/files/13125403/Dotcom_overview.zip)
