### ISSUE TITLE
Component overview gallery CTA is in Times New Roman 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom-website#941]
Link text in the thumbnail for CTA is not showing Plex but Times New Roman. This is seen on mobile Safari 

![8C3A77F2-DE3C-4D10-B6EB-785A6120C83E](https://user-images.githubusercontent.com/15144993/114949525-34af2380-9e1f-11eb-9af3-627c83b6109c.png)

**Comment by JennySanchez** [comment]
**Note:** Upon a close look, it happens when viewing the Components Overview page/ Gallery view on the mobile device. For some reason, all the font is using Times Roman but not IBM Plex.

See the recording.https://images.zenhubusercontent.com/202376156/55e4d2df-7188-411c-8a26-14685a25a157/times_new_roman_bug_fix_on_mobile_view.mov

**Comment by shixiedesign** [comment]
Anna submitted a PR for this already and it's merged https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1019

**Comment by JennySanchez** [comment]
I worked on the fix with @annawen1 .
